/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char yytext[];


static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( yytext, yytext_ptr, yyleng + 1 ); \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 183
#define YY_END_OF_BUFFER 184
static yyconst short int yy_accept[667] =
    {   0,
        0,    0,  184,  183,    1,    1,    3,  183,   48,   71,
       72,  183,  183,  179,  183,  176,  183,    4,  178,  177,
       38,  183,   39,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,   69,   70,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,   67,
       68,    2,    2,    3,   43,   66,   47,   63,   61,   62,
       64,    4,    0,   40,    0,   42,   41,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,

      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,   24,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,   25,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,   57,  182,  182,   50,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  163,  182,  182,
      182,  182,   65,    0,    0,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,

      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,   51,  182,  132,  182,   59,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,   56,  182,  166,  182,   54,  182,  182,
      182,  182,  182,  109,  182,  182,  182,  182,  182,  182,
      182,   22,  182,  182,  182,  103,  182,  182,  182,  182,
      182,   55,  182,  182,   13,  182,  182,  182,  182,  182,
      104,  182,  182,  182,   60,   53,  182,  182,   90,  182,
       58,  182,  182,  117,  182,  182,  182,  137,  182,  182,
      182,  182,  182,  182,  182,  102,  182,  182,  182,  182,

      182,   52,  182,  182,  182,  182,  182,  182,  182,  182,
      138,  182,   75,  182,  182,  182,  182,  182,  182,    0,
        0,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  152,  182,  182,  170,   80,  182,  115,  182,
      182,  182,  182,  182,  182,   30,   32,  182,  182,  182,
      182,  182,  182,  182,   10,  182,    6,   93,  182,   16,
      182,  182,  182,  182,  135,  182,  140,  139,  182,  182,
      182,  182,  134,   27,   26,  182,   12,  182,  182,  182,
      182,  182,  182,  182,  149,  182,  182,  182,  182,  182,
      153,  182,  182,  182,  182,  182,  182,  182,  110,  182,

      182,   19,  182,  165,  182,  182,   11,  106,  182,  182,
       44,  182,  182,  182,  182,  136,  182,  182,  182,  182,
      182,  160,  159,   49,  182,  182,  182,  182,  161,  162,
       96,  182,  182,  180,   18,  182,  182,  182,   95,  182,
        0,   73,  182,  182,  116,  182,  182,  182,  182,  114,
      182,  182,  182,  182,  182,  182,  182,  182,  182,   37,
      182,  182,   82,  182,  182,   81,  182,  182,   34,  175,
      133,  108,  182,   76,   28,  143,  168,  182,  182,  182,
      182,  182,  182,  167,  145,  182,  182,  181,   77,   14,
      182,  182,  182,  151,  107,  182,  182,  182,   29,  182,

      174,  154,  182,  182,  155,  111,  182,  182,  156,  182,
      182,   33,  182,  182,  182,  182,  182,    5,    7,  182,
       84,  182,  182,   79,  148,   20,  182,  182,   21,   74,
      182,  182,  182,  182,  182,  182,  131,  147,  182,   88,
      182,  182,  125,  127,  182,  182,  182,  182,  182,  118,
      182,  182,   98,  182,  141,  182,  144,  182,    9,  182,
      182,  182,  182,  182,  182,  129,  182,  182,  182,   45,
      142,   83,  182,  182,  182,  182,  182,  182,  158,  182,
       15,   94,  182,    8,  164,  182,  182,  182,   99,  182,
      182,  182,  182,  120,  112,  182,  182,   36,  182,  128,

      182,  182,   17,  130,  182,   86,   78,   23,  105,  182,
      182,  169,  182,  182,  101,  157,   91,  182,  182,  173,
      182,  123,  126,  119,  182,  182,  182,  182,  182,  182,
       31,  182,   85,  146,  150,  182,  182,   46,  182,  182,
      182,  182,  182,  182,  100,  182,  182,   35,  182,  182,
       92,  182,  182,  182,  113,  172,  124,  121,   87,   89,
      182,  182,  171,  122,   97,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    1,    1,    1,    6,    1,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,   17,   18,
       19,   20,    1,    1,   21,   22,   23,   24,   25,   26,
       21,   21,   27,   21,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   21,   38,   39,   21,   21,   21,
       40,    1,   41,    1,    1,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   21,   51,   52,   53,   54,
       55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   67,    1,   68,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    4,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    4,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[69] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,    1,    1,    1,    1,    1,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    1,
        1,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    1,    1
    } ;

static yyconst short int yy_base[668] =
    {   0,
        0,    0,  685,  686,   67,   70,   72,  665,  664,  686,
      686,   66,  663,  686,  662,  686,  661,  664,  686,  686,
       63,  659,  658,    0,   29,   55,   30,   34,  626,   36,
       64,  614,  628,   39,  627,  622,  613,  686,  686,   48,
       52,   63,   74,   73,   81,   82,  620,   91,  105,   93,
      107,   43,  114,  115,  124,  142,  143,  104,  620,  686,
      686,   92,  163,  109,  686,  686,  649,  686,  686,  686,
      686,  652,  621,  686,  615,  686,  686,    0,  618,  108,
      123,  632,  638,  619,  600,  601,  606,  601,  596,  124,
      632,  608,  593,  617,  593,  606,  594,  602,  605,  604,

      603,  580,  584,  592,  596,  130,  595,  591,  583,  591,
      576,  144,  593,  152,  152,  588,  573,  157,  159,  571,
      576,  160,  574,  151,  568,  165,  576,  573,  571,  567,
      569,  569,  160,  567,  579,  168,    0,  564,  171,  560,
      179,  163,  564,  563,  556,  553,  562,   81,  550,  174,
      560,  566,  550,  127,    0,  179,  183,  550,  563,  183,
      542,  546,  550,  538,  545,  544,  543,  181,  550,  545,
      534,  193,  537,  540,  181,  541,  539,    0,  544,  540,
      541,  540,  686,  539,  526,  543,  535,  526,  541,  188,
      550,  555,  538,  534,  520,  526,  522,  530,  524,  514,

      521,  518,  515,  544,  510,  508,  519,  505,  520,  510,
      519,  540,  511,  500,    0,  517,    0,  512,    0,  507,
      504,  513,  508,  507,  508,  493,  491,  507,  494,  487,
      481,  503,  207,  494,  497,    0,  500,    0,  498,  484,
      492,  492,  477,    0,  483,  493,  478,  487,  473,  489,
      488,  483,  475,  467,  480,    0,  464,  466,  478,  473,
      469,  468,  458,  458,    0,  471,  470,  472,  449,  465,
        0,  466,  463,  466,    0,    0,  463,  458,    0,  455,
        0,  189,  460,    0,  454,  462,  449,    0,  196,  442,
      452,  450,  444,  437,  437,    0,  438,  449,  434,  433,

      442,    0,  445,  430,  445,  428,  433,  427,  430,  432,
        0,  437,    0,  422,  427,  425,  418,  433,  425,  414,
      455,  423,  449,  426,  416,  415,  423,  443,  441,  414,
      411,  404,    0,  405,  404,    0,  439,  410,    0,  398,
      426,  411,  395,  397,  408,  226,    0,  402,  397,  408,
      404,  390,  390,  393,    0,  402,    0,    0,  396,    0,
      385,  385,  396,  391,    0,  380,    0,    0,  386,  378,
      394,  384,    0,    0,    0,  370,    0,  382,  373,  378,
      385,  378,  369,  386,    0,  377,  368,  369,  379,  377,
        0,  376,  360,  360,  377,  358,  365,  371,    0,  355,

      355,    0,  364,    0,  350,  356,    0,    0,  352,  367,
        0,  348,  347,  364,  359,    0,  349,  341,  352,  355,
      340,    0,    0,    0,  345,  340,  353,  338,    0,    0,
        0,  332,  348,    0,    0,  345,  334,  345,    0,  344,
      369,  686,  366,  332,    0,  364,  333,  330,  348,    0,
      336,  336,  357,  319,  331,  322,  325,  315,  339,    0,
      315,  326,    0,  325,  320,    0,  305,  316,  338,    0,
        0,    0,  315,    0,    0,    0,    0,  311,  318,  321,
      316,  309,  314,    0,    0,  309,  313,    0,  305,    0,
      312,  300,  312,    0,    0,  299,  299,  306,    0,  296,

        0,    0,  307,  299,    0,    0,  301,  302,    0,  297,
      298,    0,  283,  298,  319,  294,  281,    0,    0,  290,
        0,  288,  281,    0,    0,    0,  275,  275,    0,  686,
      278,  269,  276,  284,  269,  302,    0,    0,  275,    0,
      284,  261,    0,    0,  294,  277,  263,  256,  266,    0,
      273,  268,    0,  256,    0,  264,    0,  269,    0,  259,
      254,  247,  262,  256,  249,    0,  262,  261,  262,    0,
        0,    0,  263,  258,  245,  256,  241,  239,    0,  253,
        0,    0,  244,    0,    0,  233,  242,  231,    0,  271,
      261,  250,  247,    0,    0,  268,  267,    0,  242,    0,

      233,  240,    0,    0,  231,    0,    0,    0,    0,  238,
      229,    0,  236,  229,    0,    0,    0,  234,  219,    0,
      228,    0,    0,    0,  222,  241,  216,  228,  218,  230,
        0,  225,    0,    0,    0,  210,  214,    0,  223,  207,
      200,  220,  234,  204,    0,  198,  203,    0,  201,  212,
        0,  202,  210,  206,    0,    0,    0,    0,    0,    0,
      172,  107,    0,    0,    0,  686,  101
    } ;

static yyconst short int yy_def[668] =
    {   0,
      666,    1,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  666,  666,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,

      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  666,  666,  666,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,

      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,

      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  666,
      666,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,

      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      666,  666,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,

      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  666,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,

      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,  667,  667,  667,  667,  667,
      667,  667,  667,  667,  667,    0,  666
    } ;

static yyconst short int yy_nxt[755] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   24,   25,   24,   26,   27,   28,   24,   29,   24,
       24,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       24,   49,   50,   51,   52,   53,   24,   54,   55,   56,
       57,   58,   59,   24,   24,   24,   60,   61,   62,   63,
       64,   63,   63,   64,   67,   64,   73,   79,   82,   86,
       80,   74,  100,   81,   68,   83,   88,   89,   94,   91,
       87,   92,  105,   62,   63,   64,   93,  108,  101,  106,

      152,  107,   78,  153,  112,   95,  109,   75,   84,  110,
       64,  113,   64,   96,  114,  117,  111,  115,   85,  118,
      116,   97,  127,  119,  122,  123,  124,  133,  120,  125,
      128,  121,  129,  277,  145,  130,  126,  137,  131,  134,
      278,  132,  135,  138,  139,  180,  141,  146,  148,  140,
      142,  665,  149,  147,  143,  154,  159,  187,  181,  144,
      160,  150,  188,  155,   63,   63,  161,  151,  156,  162,
      285,  157,  163,  164,  158,  189,  190,  199,  165,  216,
      166,  217,  200,  167,  168,  286,  169,  171,  170,  218,
      172,  173,  176,  227,  177,  244,  174,  228,  178,  175,

      234,  179,  224,  225,  236,  230,  229,  231,  235,  241,
      247,  245,  259,  255,  262,  260,  270,  237,  242,  256,
      238,  267,  271,  302,  248,  664,  263,  280,  287,  264,
      265,  268,  289,  281,  288,  293,  303,  290,  307,  294,
      407,  312,  308,  408,  269,  313,  326,  327,  367,  413,
      309,  663,  368,  464,  465,  662,  661,  414,  660,  659,
      658,  657,  656,  655,  654,  653,  652,  651,  650,  649,
      648,  647,  646,  645,  644,  643,  642,  641,  640,  639,
      638,  637,  636,  635,  634,  633,  632,  631,  630,  629,
      628,  627,  626,  625,  624,  623,  622,  621,  620,  619,

      618,  617,  616,  615,  614,  613,  612,  611,  610,  609,
      608,  607,  606,  605,  604,  603,  602,  601,  600,  599,
      598,  597,  596,  595,  594,  593,  592,  591,  590,  589,
      588,  587,  586,  585,  584,  583,  582,  581,  580,  579,
      578,  577,  576,  575,  574,  573,  572,  571,  570,  569,
      568,  567,  566,  565,  564,  563,  562,  561,  560,  559,
      558,  557,  556,  555,  554,  553,  552,  551,  550,  549,
      548,  547,  546,  545,  544,  543,  542,  541,  540,  539,
      538,  537,  536,  535,  534,  533,  532,  531,  530,  529,
      528,  527,  526,  525,  524,  523,  522,  521,  520,  519,

      518,  517,  516,  515,  514,  513,  512,  511,  510,  509,
      508,  507,  506,  505,  504,  503,  502,  501,  500,  499,
      498,  497,  496,  495,  494,  493,  492,  491,  490,  489,
      488,  487,  486,  485,  484,  483,  482,  481,  480,  479,
      478,  477,  476,  475,  474,  473,  472,  471,  470,  469,
      468,  467,  466,  463,  462,  461,  460,  459,  458,  457,
      456,  455,  454,  453,  452,  451,  450,  449,  448,  447,
      446,  445,  444,  443,  442,  441,  440,  439,  438,  437,
      436,  435,  434,  433,  432,  431,  430,  429,  428,  427,
      426,  425,  424,  423,  422,  421,  420,  419,  418,  417,

      416,  415,  412,  411,  410,  409,  406,  405,  404,  403,
      402,  401,  400,  399,  398,  397,  396,  395,  394,  393,
      392,  391,  390,  389,  388,  387,  386,  385,  384,  383,
      382,  381,  380,  379,  378,  377,  376,  375,  374,  373,
      372,  371,  370,  369,  366,  365,  364,  363,  362,  361,
      360,  359,  358,  357,  356,  355,  354,  353,  352,  351,
      350,  349,  348,  347,  346,  345,  344,  343,  342,  341,
      340,  339,  338,  337,  336,  335,  334,  333,  332,  331,
      330,  329,  328,  325,  324,  323,  322,  321,  320,  319,
      318,  317,  316,  315,  314,  311,  310,  306,  305,  304,

      301,  300,  299,  298,  297,  296,  295,  292,  291,  284,
      283,  282,  279,  276,  275,  274,  273,  272,  266,  261,
      258,  257,  254,  253,  252,  251,  250,  249,  246,  243,
      240,  239,  233,  232,  226,  223,  222,  221,  220,  219,
      215,  214,  213,  212,  211,  210,  209,  208,  207,  206,
      205,  204,  203,  202,  201,  198,  197,  196,  195,  194,
      193,  192,  191,  186,  185,  184,   72,  183,  182,  136,
      104,  103,  102,   99,   98,   90,   77,   76,   72,   71,
       70,   69,   66,   65,  666,    3,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,

      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666
    } ;

static yyconst short int yy_chk[755] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    5,
        5,    6,    6,    7,   12,    7,   21,   25,   26,   27,
       25,   21,   34,   25,   12,   26,   28,   28,   31,   30,
       27,   30,   40,   62,   62,   62,   30,   41,   34,   40,

       52,   40,  667,   52,   42,   31,   41,   21,   26,   41,
       64,   42,   64,   31,   42,   43,   41,   42,   26,   43,
       42,   31,   45,   43,   44,   44,   44,   46,   43,   44,
       45,   43,   45,  148,   50,   45,   44,   48,   45,   46,
      148,   45,   46,   48,   48,   58,   49,   50,   51,   48,
       49,  662,   51,   50,   49,   53,   54,   80,   58,   49,
       54,   51,   80,   53,   63,   63,   55,   51,   53,   55,
      154,   53,   55,   55,   53,   81,   81,   90,   55,  106,
       55,  106,   90,   55,   55,  154,   55,   56,   55,  106,
       56,   56,   57,  114,   57,  124,   56,  114,   57,   56,

      118,   57,  112,  112,  119,  115,  114,  115,  118,  122,
      126,  124,  136,  133,  139,  136,  142,  119,  122,  133,
      119,  141,  142,  168,  126,  661,  139,  150,  156,  139,
      139,  141,  157,  150,  156,  160,  168,  157,  172,  160,
      282,  175,  172,  282,  141,  175,  190,  190,  233,  289,
      172,  654,  233,  346,  346,  653,  652,  289,  650,  649,
      647,  646,  644,  643,  642,  641,  640,  639,  637,  636,
      632,  630,  629,  628,  627,  626,  625,  621,  619,  618,
      614,  613,  611,  610,  605,  602,  601,  599,  597,  596,
      593,  592,  591,  590,  588,  587,  586,  583,  580,  578,

      577,  576,  575,  574,  573,  569,  568,  567,  565,  564,
      563,  562,  561,  560,  558,  556,  554,  552,  551,  549,
      548,  547,  546,  545,  542,  541,  539,  536,  535,  534,
      533,  532,  531,  528,  527,  523,  522,  520,  517,  516,
      515,  514,  513,  511,  510,  508,  507,  504,  503,  500,
      498,  497,  496,  493,  492,  491,  489,  487,  486,  483,
      482,  481,  480,  479,  478,  473,  469,  468,  467,  465,
      464,  462,  461,  459,  458,  457,  456,  455,  454,  453,
      452,  451,  449,  448,  447,  446,  444,  443,  441,  440,
      438,  437,  436,  433,  432,  428,  427,  426,  425,  421,

      420,  419,  418,  417,  415,  414,  413,  412,  410,  409,
      406,  405,  403,  401,  400,  398,  397,  396,  395,  394,
      393,  392,  390,  389,  388,  387,  386,  384,  383,  382,
      381,  380,  379,  378,  376,  372,  371,  370,  369,  366,
      364,  363,  362,  361,  359,  356,  354,  353,  352,  351,
      350,  349,  348,  345,  344,  343,  342,  341,  340,  338,
      337,  335,  334,  332,  331,  330,  329,  328,  327,  326,
      325,  324,  323,  322,  321,  320,  319,  318,  317,  316,
      315,  314,  312,  310,  309,  308,  307,  306,  305,  304,
      303,  301,  300,  299,  298,  297,  295,  294,  293,  292,

      291,  290,  287,  286,  285,  283,  280,  278,  277,  274,
      273,  272,  270,  269,  268,  267,  266,  264,  263,  262,
      261,  260,  259,  258,  257,  255,  254,  253,  252,  251,
      250,  249,  248,  247,  246,  245,  243,  242,  241,  240,
      239,  237,  235,  234,  232,  231,  230,  229,  228,  227,
      226,  225,  224,  223,  222,  221,  220,  218,  216,  214,
      213,  212,  211,  210,  209,  208,  207,  206,  205,  204,
      203,  202,  201,  200,  199,  198,  197,  196,  195,  194,
      193,  192,  191,  189,  188,  187,  186,  185,  184,  182,
      181,  180,  179,  177,  176,  174,  173,  171,  170,  169,

      167,  166,  165,  164,  163,  162,  161,  159,  158,  153,
      152,  151,  149,  147,  146,  145,  144,  143,  140,  138,
      135,  134,  132,  131,  130,  129,  128,  127,  125,  123,
      121,  120,  117,  116,  113,  111,  110,  109,  108,  107,
      105,  104,  103,  102,  101,  100,   99,   98,   97,   96,
       95,   94,   93,   92,   91,   89,   88,   87,   86,   85,
       84,   83,   82,   79,   75,   73,   72,   67,   59,   47,
       37,   36,   35,   33,   32,   29,   23,   22,   18,   17,
       15,   13,    9,    8,    3,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,

      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666,  666,  666,  666,  666,  666,  666,
      666,  666,  666,  666
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "Flex.l"
#define INITIAL 0
#line 4 "Flex.l"
  #include <string.h>
  #include <stdio.h>
  #include <stdlib.h>
 int count=0;
 int r=0,i=0;
 char array[100][20];
 char array2[100][20];

/*---------------- Expresiones regulares -------------------------*/
/*-------------------------Reglas-------------------------------*/
#line 771 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 30 "Flex.l"



#line 926 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 667 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 686 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 33 "Flex.l"
{/* omitir */}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 34 "Flex.l"
{/* omitir */}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 35 "Flex.l"
{/* omitir */} 
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 36 "Flex.l"
{return (NUMENTERO);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 37 "Flex.l"
{return (TIPODATO);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 38 "Flex.l"
{return (TIPODATO);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 39 "Flex.l"
{return (TIPODATO);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 40 "Flex.l"
{return (TIPODATO);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 41 "Flex.l"
{return (TIPODATO);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 42 "Flex.l"
{return (TIPODATO);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 43 "Flex.l"
{return (TIPODATO);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 44 "Flex.l"
{return (TIPODATO);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 45 "Flex.l"
{return (TIPODATO);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 46 "Flex.l"
{return (TIPODATO);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 47 "Flex.l"
{return (TIPODATO);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 48 "Flex.l"
{return (TIPODATO);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 49 "Flex.l"
{return (TIPODATO);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 50 "Flex.l"
{return (TIPODATO);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 51 "Flex.l"
{return (TIPODATO);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 52 "Flex.l"
{return (TIPODATO);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 53 "Flex.l"
{return (CICLO);} 
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 54 "Flex.l"
{return (CICLO);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 55 "Flex.l"
{return (CICLO);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 56 "Flex.l"
{return (CICLO);}	
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 57 "Flex.l"
{return (PREGUNTA);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 58 "Flex.l"
{return (ENTONCES);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 59 "Flex.l"
{return(ENTSI);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 60 "Flex.l"
{return(CLASE);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 61 "Flex.l"
{return (LECTURA);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 62 "Flex.l"
{return (LECTURA);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 63 "Flex.l"
{return (LECTURA);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 64 "Flex.l"
{return (LECTURA);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 65 "Flex.l"
{return (IMPRESION);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 66 "Flex.l"
{return (IMPRESION);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 67 "Flex.l"
{return (IMPRESION);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 68 "Flex.l"
{return (DETENER);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 69 "Flex.l"
{return (CONVERTIR);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 70 "Flex.l"
{return (MENORQUE);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 71 "Flex.l"
{return (MAYORQUE);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 72 "Flex.l"
{return (MENORIGUAL);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 73 "Flex.l"
{return (MAYORIIGUAL);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 74 "Flex.l"
{return (IGUAL);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 75 "Flex.l"
{return (DIFERENTE);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 76 "Flex.l"
{return (PASA);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 77 "Flex.l"
{return (LAMBDA);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 78 "Flex.l"
{return (NOLOCAL);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 79 "Flex.l"
{return (EXPONENTE);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 80 "Flex.l"
{return (MODULO);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 81 "Flex.l"
{return (RCUADRADA);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 82 "Flex.l"
{return (PI);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 83 "Flex.l"
{return (SUMA);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 84 "Flex.l"
{return (RESTA);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 85 "Flex.l"
{return (MULTIPLICACION);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 86 "Flex.l"
{return (DIVISION);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 87 "Flex.l"
{return (INCREMENTO);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 88 "Flex.l"
{return (DECREMENTO);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 89 "Flex.l"
{return (OPLOGOR);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 90 "Flex.l"
{return (OPLONOT);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 91 "Flex.l"
{return (OPLOGAND);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 92 "Flex.l"
{return (ASIGNACION);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 93 "Flex.l"
{return (ASIIGNACIONSUMA);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 94 "Flex.l"
{return (ASIGNACIONRESTA);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 95 "Flex.l"
{return (ASIGNACIONMULTIPLICAION);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 96 "Flex.l"
{return (ASIGNACIONDIVISION);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 97 "Flex.l"
{return (ASIGNACIONEXPONENTE);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 98 "Flex.l"
{return (ASIGNACIONMODULO);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 99 "Flex.l"
{return (KEYIZQ);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 100 "Flex.l"
{return (KEYDER);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 101 "Flex.l"
{return (CORIZQ);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 102 "Flex.l"
{return (CORDER);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 103 "Flex.l"
{return (PARIZQ);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 104 "Flex.l"
{return (PARDER);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 105 "Flex.l"
{return (DIVIZQ)}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 106 "Flex.l"
{return (DIVDER);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 107 "Flex.l"
{return (TRATAR);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 108 "Flex.l"
{return (CAPTURA);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 109 "Flex.l"
{return (ASIGNAPER);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 110 "Flex.l"
{return (FINALMENTE);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 111 "Flex.l"
{return (LANZAR);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 112 "Flex.l"
{return (LISTA);}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 113 "Flex.l"
{return (PILA);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 114 "Flex.l"
{return (COLA);}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 115 "Flex.l"
{return (NATIVO);}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 116 "Flex.l"
{return (SUPERCONST);}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 117 "Flex.l"
{return (CONTINUAR);}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 118 "Flex.l"
{return (EXTENDER);}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 119 "Flex.l"
{return (IMPLEMENTAR);}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 120 "Flex.l"
{return (IMPORTAR);}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 121 "Flex.l"
{return (INSTANCIADE);}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 122 "Flex.l"
{return (NUEVO);}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 123 "Flex.l"
{return (PRIVADO);}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 124 "Flex.l"
{return (PROTEGIDO);}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 125 "Flex.l"
{return (CASO);}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 126 "Flex.l"
{return (CAMBIO);}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 127 "Flex.l"
{return (VACIO);}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 128 "Flex.l"
{return (ESTO);}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 129 "Flex.l"
{return (SINCRONIZAR);}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 130 "Flex.l"
{return (DESCANZO);}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 131 "Flex.l"
{return (CONSOLA);}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 132 "Flex.l"
{return (INTERFAZ);}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 133 "Flex.l"
{return (PACKAGE);} 
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 134 "Flex.l"
{return (ACCESO);}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 135 "Flex.l"
{return (OBTENER);}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 136 "Flex.l"
{return (LET);}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 137 "Flex.l"
{return( FUNCION);}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 138 "Flex.l"
{return (SINVALOR);}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 139 "Flex.l"
{return (GUARD);}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 140 "Flex.l"
{return (INICIOBLOQUE);}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 141 "Flex.l"
{return (FINBLOQUE);}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 142 "Flex.l"
{return (CALCULOINICIO);}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 143 "Flex.l"
{return (MATCH);}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 144 "Flex.l"
{return (INICIORUTINA );}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 145 "Flex.l"
{return (FINRUTINA);}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 146 "Flex.l"
{return (FINIF );}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 147 "Flex.l"
{return (ABRIR );}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 148 "Flex.l"
{return (CERRAR);}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 149 "Flex.l"
{return (SALIR);}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 150 "Flex.l"
{return (CAJADETEXTO );}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 151 "Flex.l"
{return (COMBOBOX);}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 152 "Flex.l"
{return (LISTBOX);}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 153 "Flex.l"
{return (BARRADEPROGRESO);}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 154 "Flex.l"
{return (RBUTTON);}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 155 "Flex.l"
{return (CHECKBOX);}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 156 "Flex.l"
{return (PICTUREBOX);}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 157 "Flex.l"
{return (ONCLICK );}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 158 "Flex.l"
{return (CLICKDOWN );}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 159 "Flex.l"
{return (SALIDA );}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 160 "Flex.l"
{return (VISIBLE);}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 161 "Flex.l"
{return (OCULTO );}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 162 "Flex.l"
{return (HINABILITADO );}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 163 "Flex.l"
{return (HABILITADO);}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 164 "Flex.l"
{return (TODO );}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 165 "Flex.l"
{return (ALTERAR);}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 166 "Flex.l"
{return (BORRAR );}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 167 "Flex.l"
{return (COPIAR );}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 168 "Flex.l"
{return (EMPUJAR );}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 169 "Flex.l"
{return (INSERTAR);}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 170 "Flex.l"
{return (TOPE);}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 171 "Flex.l"
{return (FECHA );}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 172 "Flex.l"
{return (DATOS );}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 173 "Flex.l"
{return (CREAR );}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 174 "Flex.l"
{return (LONGITUD );}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 175 "Flex.l"
{return (LIMPIAR );}
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 176 "Flex.l"
{return (BORRAR);}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 177 "Flex.l"
{return (IGUAL);}
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 178 "Flex.l"
{return (EXCEPCION );}
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 179 "Flex.l"
{return (EXTENDER);}
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 180 "Flex.l"
{return (TITULO);}
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 181 "Flex.l"
{return (DE);}
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 182 "Flex.l"
{return (GENERAR );}
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 183 "Flex.l"
{return (AGRUPAR );}
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 184 "Flex.l"
{return (LLENO);}
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 185 "Flex.l"
{return (ALTO);}
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 186 "Flex.l"
{return (ETIQUETA);}
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 187 "Flex.l"
{return (LINEAS);}
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 188 "Flex.l"
{return (ORDENAR );}
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 189 "Flex.l"
{return (APUNTADOR);}
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 190 "Flex.l"
{return (REMOVER);}
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 191 "Flex.l"
{return (SORTEAR);}
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 192 "Flex.l"
{return (TAMAÑO);}
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 193 "Flex.l"
{return (TEXTO);}
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 194 "Flex.l"
{return (DESPUES);}
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 195 "Flex.l"
{return (ARRIBA);}
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 196 "Flex.l"
{return (VALORES);}
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 197 "Flex.l"
{return (NOMBRE);}
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 198 "Flex.l"
{return (MUERE);}
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 199 "Flex.l"
{return (VARIABLEBACIA);}
	YY_BREAK
case 168:
YY_RULE_SETUP
#line 200 "Flex.l"
{return (CLONAR);}
	YY_BREAK
case 169:
YY_RULE_SETUP
#line 201 "Flex.l"
{return (INCLUDE);}
	YY_BREAK
case 170:
YY_RULE_SETUP
#line 202 "Flex.l"
{return (LIGA);}
	YY_BREAK
case 171:
YY_RULE_SETUP
#line 203 "Flex.l"
{return (CONTENTCODEP);}
	YY_BREAK
case 172:
YY_RULE_SETUP
#line 204 "Flex.l"
{return (CLASEPRINCIPAL);}
	YY_BREAK
case 173:
YY_RULE_SETUP
#line 205 "Flex.l"
{return (REQUIERE);}
	YY_BREAK
case 174:
YY_RULE_SETUP
#line 206 "Flex.l"
{return (VARNOVACIA);}
	YY_BREAK
case 175:
YY_RULE_SETUP
#line 207 "Flex.l"
{return (ALIAS);}
	YY_BREAK
case 176:
YY_RULE_SETUP
#line 208 "Flex.l"
{return (PUNTO);}
	YY_BREAK
case 177:
YY_RULE_SETUP
#line 209 "Flex.l"
{return (PUNTOYCOMA);}
	YY_BREAK
case 178:
YY_RULE_SETUP
#line 210 "Flex.l"
{return (DOSPUNTOS);}
	YY_BREAK
case 179:
YY_RULE_SETUP
#line 211 "Flex.l"
{return (COMA);}
	YY_BREAK
case 180:
YY_RULE_SETUP
#line 212 "Flex.l"
{return (VERDADERO);}
	YY_BREAK
case 181:
YY_RULE_SETUP
#line 213 "Flex.l"
{return (FALSO);}
	YY_BREAK
case 182:
YY_RULE_SETUP
#line 215 "Flex.l"
{ 

  for (int n = 0;n < 100; n++){
            strcpy(array2,yytext);
            r = strcmp(array[n],array2);

            if(r == 0){
                 printf("\nEl id: %s se encuentra en la tabla de simbolos en la posicion: %d  \n",array[n],n);
                 break;
            }
        }
        if(r != 0){
            strcpy(array[i],yytext);
            printf("\nEl Token id: %s  esta en la posicion | %d |  \n", array[i],i);
            i++;
        }

}
	YY_BREAK
case 183:
YY_RULE_SETUP
#line 235 "Flex.l"
ECHO;
	YY_BREAK
#line 1941 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 667 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 667 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 666);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 235 "Flex.l"

/*------------------------main c--------------------------------*/
int main() {

  FILE *f1;
  f1 = fopen("texto.txt","r");
  yyin=f1; 
  yylex();

  printf("\n Tabla \n" );

 printf("\n =============================== Valores ==============================================\n");
printf("\n ====================================================================================== \n" );

	printf("\n | Posicion |    |   Valor  |");
    printf("\n |==========|    |==========|" );
    
	for(int a=0;a<i;a++){
     if(array[a]!=NULL){
	printf("\n |    %d     |    |  %s  \n",a,array[a]);
	
	}
	}
  
}



